### ISSUE TITLE
What do the 2 new buttons do?

### ISSUE THREAD

**Issue by DesperatePea** [tnychn/media-controller-extension#10]
I cant seem to figure out the difference between the two buttons added to the control panel. I am talking about the one with x in, and one with just a line inside. I figured out that the X button closes the tab, but what does the other do? What is the difference?

On the same note, it would be nice to have the option to close a media source from the media center menu, without closing the tab entirely. On chrome's media center, you could do that. 
Here is a mockup of what i mean:
![image psd](https://github.com/tnychn/media-controller-extension/assets/73502428/e62a8151-1c5e-4697-b189-e81cddf7928d)

**Comment by tnychn** [comment]
> What is the difference?

The one with x in it is for closing the tab, whereas the one with a line in it "discards" the tab, which means to stop the tab from running in background.

> it would be nice to have the option to close a media source from the media center menu, without closing the tab entirely

Sounds like the discard button already does the same. Is there any difference between these functionalities?

> Here is a mockup of what i mean

Well, I think currently though the discard and close buttons can be re-positioned into the top right corner like what you've shown in the mockup for a more intuitive interface.

**Comment by DesperatePea** [comment]
> one with a line in it "discards" the tab, which means to stop the tab from running in background.

It actually discards and refreshes the tab, which is not really what i had in mind. The feature i was talking about merely removes the media source from the list, without touching the tab at all. So, if you want it back in the media list, you can refresh the tab yourself.

**Comment by tnychn** [comment]
I see. This sounds like a nice feature to have. Though it's a bit frustrating to accommodate so many buttons inside a small popup. I will definitely figure out a better UI design.

**Comment by DesperatePea** [comment]
Yeah, that does sound nice. One small problem i have with the current "discard tab" button is, lets say i browse tumblr or reddit. Often, the media centre lists reddit as a media source because i played a video, but i scrolled past this. This remains in the media centre list until i delete the tab. However, if i were to click the discard tab button, it refreshes my reddit tab, and therefore i end up losing all my progress.

Does that make sense? I think just simply removing reddit from the media centre without touching the tab would be a little bit better.

**Comment by trlkly** [comment]
You might consider putting some options behind a (...) button or right click to reduce the number of buttons.

**Comment by vlakoff** [comment]
I might suggest to add a bit of spacing between the "Remove from List" and "Close Tab" buttons, to prevent accidentally clicking on the former instead of the latter.

Rationale: accidentally clicking on "Remove from List" may be frustrating, as in order to get back the relevant tab in the extension popup, the user has to find back the browser tab and "reactivate" it by some means (e.g. reload page, pause-play having sound enabled…)

Similarly, I suppose that accidentally clicking on the latter instead of the former may be frustrating too.
