### ISSUE TITLE
Improve controls contrast on "medium colored" backgrounds

### ISSUE THREAD

**Issue by vlakoff** [tnychn/media-controller-extension#14]
Given the background color of the tab, the algorithm to determine the controls color is currently (see in [popup/index.js](https://github.com/tnychn/media-controller-extension/blob/main/src/popup/index.js)):

```
r = 255 - r
g = 255 - g
b = 255 - b
```

For example, provided a `174 161 158` background, the controls color will be `81 94 97`.

This works well with clearly light or dark backgrounds, but if the background is in mid-range, the controls color will be very close; they could even be the same. Think of the most extreme case, `128 128 128`.

Note it is unrelated to the background being light or dark.

As an example, see the 2nd tab here:

![media-controller-extension__contrast](https://github.com/user-attachments/assets/c3673648-81ab-4995-89e8-ac62cd75521d)

Therefore, we need to figure out a better algorithm to determine the controls color.

As a starting point:

In web accessibility, a formula to determine the brightness is:

```
((299 x R) + (587 x G) + (114 x B)) / 1000
```

Then, use dark text if brightness > 125, or light text if brightness <= 125.

Considering this, adopting a brightness-based approach might provide a more reliable solution for determining the controls color.

**Comment by vlakoff** [comment]
I added `textColorV4`. It compares the results from `textColorV1` and `textColorV2`, and picks the one with the best contrast.

I'm beginning to be satisfied with the results. There are still cases that are unsatisfactory, but they are not very numerous, and definitely fewer than currently. And I'm thinking of an even better approach.

**Comment by vlakoff** [comment]
I added `textColorV5`. It uses the same approach as `textColorV2`, but instead of offsetting the color one way or the other, it offsets the color both ways, then selects the one with the best contrast.

Note that one of the offset colors always has more contrast than the bare complement color.

This time, I'm very happy with the results.

**Comment by vlakoff** [comment]
Here is how it would integrate into [popup/index.js](https://github.com/tnychn/media-controller-extension/blob/main/src/popup/index.js):

```js
const fgColor = ((background) => {
  function complementaryColor(rgb) {
    return [255 - rgb[0], 255 - rgb[1], 255 - rgb[2]];
  }
  function luminance(rgb) {
    const a = rgb.map((v) => {
      v /= 255;
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    });
    return a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;
  }
  function contrast(rgb1, rgb2) {
    const lum1 = luminance(rgb1);
    const lum2 = luminance(rgb2);
    const brightest = Math.max(lum1, lum2);
    const darkest = Math.min(lum1, lum2);
    return (brightest + 0.05) / (darkest + 0.05);
  }
  function rgbToHex(rgb) {
    return '#' + rgb.map(value => value.toString(16).padStart(2, '0')).join('');
  }
  const complement = complementaryColor(background);
  const diffTo255 = 255 - Math.max(...complement);
  const complementLighter = complement.map(c => c + diffTo255);
  const contrastLighter = contrast(background, complementLighter);
  const diffTo0 = Math.min(...complement);
  const complementDarker = complement.map(c => c - diffTo0);
  const contrastDarker = contrast(background, complementDarker);
  return rgbToHex(contrastLighter > contrastDarker ? complementLighter : complementDarker);
})(tab.color);
```

I aimed to maintain your coding style. Before submitting a PR, I would appreciate your review and approval. Alternatively, feel free to commit it on your end.

**Comment by tnychn** [comment]
Impressive! The color problem has been bothering for quite some time, though I don't have time to dig into it.
Your code works great. Thanks for the solution!
